name: shopzy_grocery_user
description: "A new Flutter project."
#version:  3.16.9
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  connectivity: ^3.0.6
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  otp_text_field: ^1.1.3
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  location_geocoder: ^1.0.5
  geocoding: ^2.0.4
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.1.0
  image_picker: ^1.1.1
  phone_number: ^2.0.1
  firebase_messaging: ^14.7.15
  firebase_core: ^2.31.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/temperary_images/
    - assets/languages/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
